accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountDeleteView, UsersListView

app_name = 'accounts'
urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordChangeView.as_view(), name='password'),
    path('delete', AccountDeleteView.as_view(), name='profile_delete'),
    path('leaders', UsersListView.as_view(), name='leaders')
]

app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('quizes/', include('quiz.urls'))
]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from PIL import Image
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(null=True, default='default.jpg', upload_to='covers/')
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

quiz/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from accounts.models import User

# Create your models here.
from core.models import BaseModel
from core.utils import generate_uuid


class Test(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    # topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def questions_count(self):
        return self.questions.count()

    def _get_best_result(self):
        if not self.results.all():
            return {'score': 'N/A', 'user': 'N/A'}
        _results_list = []
        for result in self.results.all():
            _results_list.append(result.num_correct_answers)
        best_result = max(_results_list)
        best_users = []
        time_spend = []
        for result in self.results.all():
            if result.num_correct_answers == best_result:
                best_users.append(result.user.last_name)
                time_spend.append(result.time_spent())
        if len(best_users) > 1:
            leader_dict = dict(zip(time_spend, best_users))
            min_time = min(time_spend)
            best_users = leader_dict[min_time]

        return {'score': best_result, 'user': best_users}

    def get_best_result_score(self):
        return self._get_best_result()['score']

    def get_best_user(self):
        return self._get_best_result()['user']

    def get_time_last_run(self):
        return self.results.last().create_date

    def has_unfinished_run(self):
        return self.results.exclude(
            state=Result.STATE.FINISHED
        ).exists()

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Choice(models.Model):
    CHOICE_MIN_LIMIT = 1
    CHOICE_MAX_LIMIT = 3

    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True)

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )

    def update_result(self, order_number, question, selected_choices):
        correct_choices = [
            choice.is_correct
            for choice in question.choices.all()
        ]

        correct_answer = True
        for x, y in zip(correct_choices, selected_choices):
            correct_answer &= (x == y)

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number
        if order_number == question.test.questions_count():
            self.state = self.STATE.FINISHED
        self.save()

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    def success_rate(self):
        result = round(self.num_correct_answers / self.test.questions_count() * 100, 2)
        return f' {result} %'

    def time_spent(self):
        time_spent = self.write_date - self.create_date
        return time_spent

    def save(self, *args, **kwargs):
        if self.state == self.STATE.FINISHED:
            self.user.rating += self.points()
            self.user.save()
        super().save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import User


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'image']

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, LogoutView, LoginView
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, CreateView, ListView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm
from accounts.models import User


class UsersListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'leaderboard.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.exclude(rating=0).order_by('-rating')
        return context


class AccountPasswordChangeView(PasswordChangeView):
    model = User
    template_name = 'password_change.html'
    success_url = reverse_lazy('index')


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User successfully registered')
        return result


class AccountLoginView(LoginView):
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'User {self.request.user} successfully logged in')
        return result


class AccountUpdateView(UpdateView):
    model = User
    template_name = 'profile.html'
    success_url = reverse_lazy('index')
    form_class = AccountUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f" Profile: User {self.request.user} has succesfully updated")
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(self.request, f'User {self.request.user} has been logged out')
        return super().dispatch(request, *args, **kwargs)


class AccountDeleteView(DeleteView):
    def get(self, request, *args, **kwargs):
        user = self.request.user

        return render(request,
                      template_name='profile:delete.html',
                      context={'user': user}
                      )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user.delete()

        return render(request,
                      template_name='index.html',
                      context={'user': user}
                      )

accounts/templates/leaderboard.html
{% extends 'base.html' %}

{% block header %}
    <h1>Leaderboard</h1>
{% endblock %}

{% block content %}

<table class="table table-hover">
          <tr style="background:black; color:white">
            <th>#</th>
            <th></th>
            <th>User</th>
            <th>Rating</th>
          </tr>
    {% for user in users %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td> <img class="rounded-circle" src="{{ user.image.url }}" width="50" height="50"></td>
            <td>{{ user }}</td>
            <td>{{ user.rating }}</td>
        </tr>
    {% endfor %}

</table>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Login as user</h1>
{% endblock %}

{% block content %}

    <div class="container">



            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Login</button>

            </form>

    </div>
{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">User is logged out</h1>
{% endblock %}

{% block content %}
    <div class="d-grid gap-2 col-4 mx-auto">
        <a href="{% url 'accounts:login' %}" class="btn btn-primary" type="button">Login</a>
        <a href="{% url 'accounts:registration' %}" class="btn btn-success" type="button">Register</a>
    </div>
{% endblock %}

accounts/templates/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Change password</h1>
{% endblock %}

{% block content %}

    <div class="container">



            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Submit</button>

            </form>

    </div>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Update Profile</h1>
{% endblock %}

{% block content %}
    <div class="container">
             <form method='post' enctype="multipart/form-data">
                  {% csrf_token %}

                    <div class="media">
                        <div class="img-circle.vert">
                            <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.image.url }}">
                        </div>
                        <div class="media-body  p-3 m-3">
                            <h2 class="account-heading">{{ user.username }}</h2>
                            <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                            <p class="text-secondary">{{ user.email }}</p>
                        </div>
                    </div>
                 <display>Results</display>
             <table class="table table-striped table-hover">
                  <tr>
                    <th>#</th>
                    <th>Test</th>
                    <th>Create date</th>
                    <th>Write date</th>
                    <th>User</th>
                    <th>Points</th>
                    <th>State</th>
                  </tr>
                {% for result in user.results.all %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ result.test }}</td>
                        <td>{{ result.create_date }}</td>
                        <td>{{ result.write_date }}</td>
                        <td>{{ result.user }}</td>
                        <td>{{ result.points }}</td>
                        <td>{{ result.get_state_display }}</td>
                      </tr>
                {% endfor %}

            </table>
                    {{ form|crispy }}

                  <input class="btn btn-success btn-lg mt-2" type="submit" value="Save">
                    <a class="btn btn-danger btn-lg mt-2" href="{% url 'accounts:profile_delete'  %}" role="button">Delete</a>
             </form>

    </div>
{% endblock %}

accounts/templates/profile:delete.html
{% extends 'base.html' %}

{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Delete profile</h1>
{% endblock %}

{% block content %}
    <div class="container" style="text-align: center">

        <h3> Do you really want to delete Profile: {{user.username}} ? </h3>

        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger btn-lg mt-2" type="submit" value="Delete">
            <a class="btn btn-warning btn-lg mt-2" href="{% url 'accounts:profile'  %}" role="button">Cancel</a>
        </form>

    </div>
{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Create account</h1>
{% endblock %}

{% block content %}

    <div class="container">



            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Create</button>

            </form>

    </div>
{% endblock %}