accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountDeleteView, UsersListView

app_name = 'accounts'
urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordChangeView.as_view(), name='password'),
    path('delete', AccountDeleteView.as_view(), name='profile_delete'),
    path('leaders', UsersListView.as_view(), name='leaders')
]

app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('quizes/', include('quiz.urls'))
]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path

from quiz.views import TestDetailView, TestListView, TestResultQuestionView, TestResultCreateView, \
    TestResultDetailsView, TestResultUpdateView, TestResultDeleteView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
    path('<uuid:uuid>/results/create', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details', TestResultDetailsView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update', TestResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next', TestResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete', TestResultDeleteView.as_view(), name='result_delete'),

]

core/models.py
from django.db import models


class BaseModel(models.Model):
    class Meta:
        abstract = True

    create_date = models.DateTimeField(null=True, auto_now_add=True)
    write_date = models.DateTimeField(null=True, auto_now=True)

core/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request,
                  template_name='index.html')

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


{% block title %}
        <title>Quiz</title>
{% endblock %}

</head>
<body>

<div class="container-fluid">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid" style="margin-left:50px">
        <a class="navbar-brand" href="{% url 'index' %}">Quiz</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:leaders' %}">Leaders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'tests:list' %}">Tests</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <ul class="navbar-nav ">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>

                {%  if user.is_authenticated %}
                    <li class="nav-item">
                        <img alt="Profile pic" width="35" height="35" class="rounded-circle" src="{{ user.image.url }}">
                    </li>

                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                      </li>

                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                      </li>

                {% else %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:registration' %}">Register</a>
                      </li>

                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                      </li>
                {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
            {% include 'includes/messages.html' %}

            <div class="border rounded text-center p-3 m-3 mb-5 shadow">
                {% block header %}
                    <h1>
                        Welcome to Quiz!!!
                    </h1>
                {% endblock %}
            </div>

            {% block content %}
            {% endblock %}
      </div>


</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

core/templates/index.html
{% extends 'base.html' %}

{% block greetings %}
    <div class="container mt-3" style="border-style:dotted;  border-width:2px;">
        <h1 style="text-align:center; font-size:300%; color:red;">WELCOME TO Quiz!</h1>
    </div>
{% endblock %}

{% block main %}

{% endblock %}